formatter: markdown

header-from: main.tf

content: |-
  {{ .Header }}

  ## Uso

  ### Ejemplo Simple

  ```hcl
  module "example" {
    source = "github.com/tu-usuario/tu-modulo-terraform"

    name        = "mi-recurso"
    environment = "production"
    additional_tags = {
      Owner = "DevOps Team"
    }
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
